import './globals.css'
import { Inter } from 'next/font/google'
import { Header } from "../components/header/header"
import { Footer } from "../components/footer/footer"
import { EndpointUrls } from '@/utils/endpoint-urls'
import { Cart } from '@/components/cart/cart'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Тестовое задание для Lichi',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const cartList = await getCartList();

  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />  
        {children}
        <Cart />
        <Footer />
      </body>
    </html>
  )
}

async function getCartList () {
  const result = await fetch(EndpointUrls.GET_ADDED_LIST, {
    method: 'POST'
  })
  
  return result  
}
